-- ==========================================
-- AI Update Portal v2.5 Supabase Database Schema (Secure Version)
-- ==========================================

-- 1. Posts (뉴스 게시글) 테이블 생성
DROP TABLE IF EXISTS public.posts CASCADE;
CREATE TABLE public.posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title JSONB NOT NULL,
    category_l1 TEXT NOT NULL,
    program_l2 TEXT NOT NULL,
    company TEXT NOT NULL,
    status_badge TEXT,
    tech_status TEXT,
    summary JSONB,
    content_body JSONB NOT NULL,
    url TEXT,
    is_important BOOLEAN DEFAULT FALSE,
    views INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- ==========================================
-- 🔒 2. SECURITY: Row Level Security (RLS)
-- ==========================================
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;

-- ✅ 허용 정책: 누구나(익명 사용자 포함) 뉴스를 "읽을" 수 있음
DROP POLICY IF EXISTS "Anyone can read posts" ON public.posts;
CREATE POLICY "Anyone can read posts" 
ON public.posts FOR SELECT 
USING (true);

-- 🚫 차단 정책: 익명/일반 사용자의 INSERT, UPDATE, DELETE 완전 차단
-- (정책을 정의하지 않으면 기본적으로 차단되나, 확실한 보안을 위해 명시적 룰을 추가하거나 
-- Service Role(크롤러 봇)만 가능함을 원칙으로 함. Service Role은 RLS를 우회함.)
DROP POLICY IF EXISTS "Deny insert for anon" ON public.posts;
CREATE POLICY "Deny insert for anon" ON public.posts FOR INSERT WITH CHECK (false);

DROP POLICY IF EXISTS "Deny update for anon" ON public.posts;
CREATE POLICY "Deny update for anon" ON public.posts FOR UPDATE USING (false) WITH CHECK (false);

DROP POLICY IF EXISTS "Deny delete for anon" ON public.posts;
CREATE POLICY "Deny delete for anon" ON public.posts FOR DELETE USING (false);

-- ==========================================
-- 🛠 3. SECURITY: 조회수 조작 방지용 RPC (Stored Procedure)
-- ==========================================
-- 해커가 임의로 조회수를 100만으로 조작하는 UPDATE 쿼리를 막고, 
-- 오직 1씩만 안전하게 증가시키는 서버 내부 함수를 제공합니다.
CREATE OR REPLACE FUNCTION increment_view_count(p_id BIGINT)
RETURNS void AS $$
BEGIN
  UPDATE public.posts
  SET views = views + 1
  WHERE id = p_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
-- SECURITY DEFINER 속성 덕분에 클라이언트가 권한이 없어도 이 함수 내부의 UPDATE 쿼리만은 실행 가능함.

-- ==========================================
-- 🌐 4. Realtime 활성화 (필수)
-- ==========================================
-- 클라이언트가 변경 사항(크롤러 새 글)을 즉각 수신할 수 있도록 활성화
ALTER PUBLICATION supabase_realtime ADD TABLE public.posts;
