-- ==========================================
-- AI Update Portal v2.5 Supabase Database Schema
-- ==========================================

-- 1. Comments (댓글) 테이블 생성
DROP TABLE IF EXISTS public.comments CASCADE;
CREATE TABLE public.comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL,
    user_id UUID REFERENCES auth.users(id), -- Supabase Auth 연동
    user_name TEXT NOT NULL,
    avatar TEXT,
    comment_text TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    is_blinded BOOLEAN DEFAULT FALSE
);

-- 2. Row Level Security (RLS) 설정 (프론트엔드 직접 접근 허용)
ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;

-- 누구나 댓글을 읽을 수 있음
DROP POLICY IF EXISTS "Anyone can read comments" ON public.comments;
CREATE POLICY "Anyone can read comments" 
ON public.comments FOR SELECT 
USING (true);

-- 로그인한 사용자만 댓글을 작성할 수 있음
DROP POLICY IF EXISTS "Authenticated users can insert comments" ON public.comments;
CREATE POLICY "Authenticated users can insert comments" 
ON public.comments FOR INSERT 
WITH CHECK (auth.role() = 'authenticated');

-- 3. (선택) Posts (뉴스 게시글) 테이블 생성
-- 백엔드가 직접 AI 뉴스를 수집해 넣을 공간
DROP TABLE IF EXISTS public.posts CASCADE;
CREATE TABLE public.posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title JSONB NOT NULL,
    category_l1 TEXT NOT NULL,
    program_l2 TEXT NOT NULL,
    company_l3 TEXT NOT NULL,
    status_badge TEXT,
    tech_status TEXT,
    summary JSONB,
    summary_3lines JSONB,
    content_body JSONB NOT NULL,
    views INTEGER DEFAULT 0,
    comments_count INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;

-- 누구나 뉴스를 읽을 수 있음
DROP POLICY IF EXISTS "Anyone can read posts" ON public.posts;
CREATE POLICY "Anyone can read posts" 
ON public.posts FOR SELECT 
USING (true);
