-- ==========================================
-- AI Update Portal v2.5 Supabase Database Schema (Secure Version)
-- ==========================================

-- 1. Posts (뉴스 게시글) 테이블 생성
DROP TABLE IF EXISTS public.posts CASCADE;
CREATE TABLE public.posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title JSONB NOT NULL,
    category_l1 TEXT NOT NULL,
    program_l2 TEXT NOT NULL,
    company TEXT NOT NULL,
    status_badge TEXT,
    tech_status TEXT,
    summary JSONB,
    content_body JSONB NOT NULL,
    url TEXT,
    is_important BOOLEAN DEFAULT FALSE,
    views INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- ==========================================
-- 🔒 2. SECURITY: Row Level Security (RLS)
-- ==========================================
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;

-- ✅ 허용 정책: 누구나(익명 사용자 포함) 뉴스를 "읽을" 수 있음
DROP POLICY IF EXISTS "Anyone can read posts" ON public.posts;
CREATE POLICY "Anyone can read posts" 
ON public.posts FOR SELECT 
USING (true);

-- 🚫 차단 정책: 익명/일반 사용자의 INSERT, UPDATE, DELETE 완전 차단
-- (정책을 정의하지 않으면 기본적으로 차단되나, 확실한 보안을 위해 명시적 룰을 추가하거나 
-- Service Role(크롤러 봇)만 가능함을 원칙으로 함. Service Role은 RLS를 우회함.)
DROP POLICY IF EXISTS "Deny insert for anon" ON public.posts;
CREATE POLICY "Deny insert for anon" ON public.posts FOR INSERT WITH CHECK (false);

DROP POLICY IF EXISTS "Deny update for anon" ON public.posts;
CREATE POLICY "Deny update for anon" ON public.posts FOR UPDATE USING (false) WITH CHECK (false);

DROP POLICY IF EXISTS "Deny delete for anon" ON public.posts;
CREATE POLICY "Deny delete for anon" ON public.posts FOR DELETE USING (false);

-- ==========================================
-- 🛠 3. SECURITY: 조회수 조작 방지용 RPC (Stored Procedure)
-- ==========================================
-- 해커가 임의로 조회수를 100만으로 조작하는 UPDATE 쿼리를 막고, 
-- 오직 1씩만 안전하게 증가시키는 서버 내부 함수를 제공합니다.
CREATE OR REPLACE FUNCTION increment_view_count(p_id BIGINT)
RETURNS void AS $$
BEGIN
  UPDATE public.posts
  SET views = views + 1
  WHERE id = p_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
-- SECURITY DEFINER 속성 덕분에 클라이언트가 권한이 없어도 이 함수 내부의 UPDATE 쿼리만은 실행 가능함.

-- ==========================================
-- 🌐 4. Realtime 활성화 (필수)
-- ==========================================
-- 클라이언트가 변경 사항(크롤러 새 글)을 즉각 수신할 수 있도록 활성화
ALTER PUBLICATION supabase_realtime ADD TABLE public.posts;

-- ==========================================
-- 💬 5. Comments (댓글) 테이블 생성 및 강력한 보안 설정(RLS)
-- ==========================================
DROP TABLE IF EXISTS public.comments CASCADE;
CREATE TABLE public.comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT REFERENCES public.posts(id) ON DELETE CASCADE,
    user_id UUID NOT NULL,
    user_name TEXT NOT NULL,
    avatar TEXT,
    comment_text TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- RLS(행 수준 보안) 활성화: 이 설정이 없으면 누구나 데이터를 지우고 쓸 수 있음
ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;

-- ✅ 정책 1: 누구나(로그인 안해도) 댓글을 읽을 수 있음
CREATE POLICY "Anyone can read comments" 
ON public.comments FOR SELECT 
USING (true);

-- ✅ 정책 2: 오직 로그인한 사용자만 '자신의 ID'로 댓글 작성 가능
CREATE POLICY "Users can insert their own comments" 
ON public.comments FOR INSERT 
WITH CHECK (auth.uid() = user_id);

-- ✅ 정책 3: 오직 로그인한 사용자만 '자신이 쓴 댓글'만 삭제 가능
CREATE POLICY "Users can delete their own comments" 
ON public.comments FOR DELETE 
USING (auth.uid() = user_id);

-- 🚫 정책 4: 댓글 수정(UPDATE)은 불필요하므로 원천 차단
CREATE POLICY "Deny update for comments" 
ON public.comments FOR UPDATE 
USING (false) WITH CHECK (false);

-- 실시간 업데이트(Realtime) 채널에 comments 테이블 추가
ALTER PUBLICATION supabase_realtime ADD TABLE public.comments;

-- ==========================================
-- 🗑️ 6. SECURITY: 회원 탈퇴 기능 (RPC)
-- ==========================================
-- 클라이언트는 보안상 기본적으로 auth.users 테이블을 수정하거나 삭제할 수 없습니다.
-- 따라서 서버 측 함수(SECURITY DEFINER)를 우회로로 제공하되, 오직 로그인한 본인(auth.uid())만 삭제하도록 제한합니다.
CREATE OR REPLACE FUNCTION public.delete_user()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  -- 현재 로그인한 사용자의 ID로 auth.users 테이블에서 해당 레코드를 삭제합니다.
  -- Supabase에서는 auth.users 에서 지워지면 ON DELETE CASCADE 로 연결된 데이터(comments 등)도 삭제될 수 있습니다.
  DELETE FROM auth.users WHERE id = auth.uid();
END;
$$;
