name: Realtime AI News Crawler

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  crawl-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24' # 에러의 원인이었던 캐시 옵션을 아예 삭제하고 버전 24로 올림!

    - name: Install Dependencies
      working-directory: ./backend
      run: npm install

    - name: Run Crawler
      working-directory: ./backend
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      run: node crawler.js
